set(CPACK_PACKAGE_NAME "TinyFrame"
    CACHE STRING "TinyFrame"
)
set(CPACK_PACKAGE_VENDOR "Trung Dao Quoc <daotrung1603@gmail.com>")
set(CPACK_PACKAGE_CONTACT "Trung Dao Quoc <daotrung1603@gmail.com>")
set(CPACK_PACKAGE_VERSION_MAJOR "${CMAKE_PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${CMAKE_PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${CMAKE_PROJECT_VERSION_PATCH}")
set(CPACK_STRIP_FILES YES)
set(CPACK_VERBATIM_VARIABLES true)
set(CPACK_SOURCE_IGNORE_FILES .git/ .github/ .vscode/ .mypy_cache/ _CPack_Packages/
${CMAKE_BINARY_DIR}/ ${PROJECT_BINARY_DIR}/
)
set(CPACK_PACKAGE_NAME ${PROJECT_NAME}
    CACHE STRING "The resulting package name"
)

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Template Game for C++ project"
    CACHE STRING "Package description for the package metadata"
)

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)
set(CPACK_DEB_COMPONENT_INSTALL YES)
set(CPACK_GENERATOR "ZIP;TGZ") 
set(CPACK_SOURCE_GENERATOR "TGZ")

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(CPACK_PACKAGING_INSTALL_PREFIX "/opt/some")
  set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
  set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)
  set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Trung Dao Quoc <daotrung1603@gmail.com>")
  set(
    CPACK_INSTALL_DEFAULT_DIRECTORY_PERMISSIONS
    OWNER_READ OWNER_WRITE OWNER_EXECUTE
    GROUP_READ GROUP_EXECUTE
    WORLD_READ WORLD_EXECUTE
  )
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  set(CPACK_NSIS_MODIFY_PATH "ON")
  set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY ${PROJECT_NAME})
  if(USE_NSIS)
    set(CPACK_GENERATOR "NSIS")
  else(USE_NSIS)
    set(CPACK_GENERATOR "ZIP")
  endif(USE_NSIS)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
endif()


#CPACK_PACKAGE_DESCRIPTION_FILE
#CPACK_RESOURCE_FILE_WELCOME
#CPACK_RESOURCE_FILE_LICENSE
#CPACK_RESOURCE_FILE_README
include(CPack)