set(CPACK_PACKAGE_VENDOR "Trung Dao Quoc <trung.daoquoc@gmail.com>")
set(CPACK_PACKAGE_VERSION_MAJOR "${CMAKE_PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${CMAKE_PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${CMAKE_PROJECT_VERSION_PATCH}")
set(CPACK_STRIP_FILES "TRUE")
set(CPACK_VERBATIM_VARIABLES true)
set(CPACK_SOURCE_IGNORE_FILES .git/ .github/ .vscode/ .mypy_cache/ _CPack_Packages/
${CMAKE_BINARY_DIR}/ ${PROJECT_BINARY_DIR}/
)
set(CPACK_PACKAGE_NAME ${PROJECT_NAME}
    CACHE STRING "The resulting package name"
)

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Simple C++ application"
    CACHE STRING "Package description for the package metadata"
)

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  # Linux-specific stuff
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
endif()
set(CPACK_GENERATOR "ZIP;TGZ")

#CPACK_PACKAGE_DESCRIPTION_FILE
#CPACK_RESOURCE_FILE_WELCOME
#CPACK_RESOURCE_FILE_LICENSE
#CPACK_RESOURCE_FILE_README
include(CPack)